# Site settings
title: Weishuai Zeng
description: Weishuai's Homepage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi! I'm Weishuai Zeng.
user_description: I'm Weishuai Zeng, a final-year undergraduate majoring in Artificial Intelligence at EECS, Peking University. My research is centered on building a general-purpose humanoid robots for open-world environments, with an emphasis on specific issues including Hierarchical Planning and Control, Perception and Recognition, Scene and Object Interaction, Foundation Models and Cross-embodiment Learning. Recently, I'm fascinated by the idea of finding a unified abstraction for all the existing researches on humanoid robots and devoted to achieving the "GPT moment" for humanoid robots. I am now working with Dr. Jingbo Wang and Dr.Jiangmiao Pang at InternRobotics, Shanghai Artificial Intelligence Laboratory. Previously, I interned at Beijing Academy of Artificial Intelligence (BAAI) where I am enabled to self-explore domains including Large Foundation models, Embodied Agents, Virtual Avatars and Animation. All these things serve as foundation for my passion on humanoid robots, which I really appreciate. I welcome discussions and collaborations on any of the topics above. So feel free to contact me as I firmly believe collaboration brings real science.
user_title: AI Researcher and Roboticist at EECS, PKU.
email: mailto:weishuai107@gmail.com
twitter_username: https://x.com/weishuaizeng
github_username:  https://github.com/zengweishuai

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
